### ISSUE TITLE
Add a debug option for the library.

### ISSUE THREAD

**Issue by vorillaz** [amannn/next-intl#136]
### Is your feature request related to a problem? Please describe.

Once again, I would say a big “Thank You” for your efforts and this amazing library.

Essentially, it would be incredible if we could have a global debug option for our translators.
We are using a centralized repository for consuming and updating the translations, it's a simple Strapi web service, the translations are parsed and fetched through API calls at build time.

It's a bit cumbersome though for our people to go through our staging environment and track down the key they should update in the database, since we could have similar values for different keys.

### Describe the solution you'd like

Next.js works great with `env` variables, thus it would be possible to add a debug variable like `NEXT_PUBLIC_I18N_DEBUG=true`, the `next.config.js` would be an option as well adding this flag, this flag could get injected into the provider.

Upon rendering, the translated text the renderer should wrap the translated item with a simple `<span />` and attach the key as an attribute.

```jsx
const wrapOnDebug = (el, i18nKey) => <span data-i18n-key={i18nKey}>{el}</span>
```
Visualizing and debugging requires no JavaScript at all, a simple CSS snippet could do the trick.

```css
[data-i18n-key] {
  position:relative; 
  border-bottom:1px dashed #000;
}

[data-i18n-key]:before {
  content: attr(data-i18n-key); /* here's the magic */
  position:absolute;
  
  /* vertically center */
  top:50%;
  transform:translateY(-50%);
  
  /* move to right */
  left:100%;
  margin-left:15px; /* and add a small left margin */
  
  /* basic styles */
  width:200px;
  padding:10px;
  border-radius:10px;
  background:#000;
  color: #fff;
  text-align:center;

  display:none; /* hide by default */
}

[data-i18n-key]:hover:before {
  display:block;
}
```

### Describe alternatives you've considered

Any other suggestion would be great and really helpful, I can work on this one and provide a POC in no time :)
